name: build

on:
  push:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Remove old release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release delete latest --yes || true
          git push origin :refs/tags/latest || true
      - name: Create new release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          name: Latest build

  linux-x86_64:
    runs-on: ubuntu-latest
    needs: release
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt install make ninja-build pkg-config libssl-dev libsdl2-dev libpixman-1-dev libpixman-1-0 libglib2.0-dev
      - name: Configure & build
        run: |
          mkdir build
          cd build
          ../configure --enable-sdl --disable-cocoa --target-list=arm-softmmu --disable-capstone --disable-slirp --extra-cflags=-I/usr/include/openssl --extra-ldflags='-lcrypto' --disable-werror --enable-pie
          make
      - name: Package
        run: |
          mkdir linux-x86_64
          cd linux-x86_64
          cp ../build/arm-softmmu/qemu-system-arm qemu-ios
          wget https://github.com/devos50/qemu-ios/releases/download/n72ap_v1/nor_n72ap.bin
          wget https://github.com/devos50/qemu-ios/releases/download/n72ap_v1/bootrom_240_4
          wget https://github.com/devos50/qemu-ios/releases/download/n72ap_v1/nand_n72ap.zip
          unzip nand_n72ap.zip
          cp -r nand_n72ap/nand .
          rm -rvf nand_n72ap
          cd ..
          zip -r linux-x86_64.zip linux-x86_64
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          files: |
            linux-x86_64.zip

  macos-arm64:
    runs-on: macos-latest
    needs: release
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          brew install glib ninja pixman pkg-config sdl2 openssl
          python3 -m pip install --break-system-packages distlib setuptools wheel
      - name: Configure & build
        run: |
          mkdir build
          cd build
          ../configure --enable-sdl --target-list=arm-softmmu --disable-capstone --disable-pie --disable-slirp --extra-cflags=-I/opt/homebrew/opt/openssl@3/include --extra-ldflags='-L/opt/homebrew/opt/openssl@3/lib -lcrypto'
          make
      - name: Package
        run: |
          mkdir macos-arm64
          cd macos-arm64
          cp ../build/arm-softmmu/qemu-system-arm qemu-ios
          curl -O https://github.com/devos50/qemu-ios/releases/download/n72ap_v1/nor_n72ap.bin
          curl -O https://github.com/devos50/qemu-ios/releases/download/n72ap_v1/bootrom_240_4
          curl -O https://github.com/devos50/qemu-ios/releases/download/n72ap_v1/nand_n72ap.zip
          unzip nand_n72ap.zip
          cp -r nand_n72ap/nand .
          rm -rvf nand_n72ap
          cd ..
          zip -r macos-arm64.zip macos-arm64
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          files: |
            macos-arm64.zip


  macos-x86_64:
    runs-on: macos-26-intel
    needs: release
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          brew install glib ninja pixman pkg-config sdl2 openssl
          python3 -m pip install --break-system-packages distlib setuptools wheel
      - name: Configure & build
        run: |
          mkdir build
          cd build
          ../configure --target-list=arm-softmmu --extra-cflags=-I/usr/local/opt/openssl@3/include --extra-ldflags='-L/usr/local/opt/openssl@3/lib -lcrypto'
          make
      - name: Package
        run: |
          mkdir macos-x86_64
          cd macos-x86_64
          cp ../build/arm-softmmu/qemu-system-arm qemu-ios
          curl -O https://github.com/devos50/qemu-ios/releases/download/n72ap_v1/nor_n72ap.bin
          curl -O https://github.com/devos50/qemu-ios/releases/download/n72ap_v1/bootrom_240_4
          curl -O https://github.com/devos50/qemu-ios/releases/download/n72ap_v1/nand_n72ap.zip
          unzip nand_n72ap.zip
          cp -r nand_n72ap/nand .
          rm -rvf nand_n72ap
          cd ..
          zip -r macos-x86_64.zip macos-x86_64
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          files: |
            macos-x86_64.zip


  windows:
    runs-on: windows-latest
    needs: release
    steps:
      - uses: actions/checkout@v4
      - name: Install MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: >-
            git
            base-devel
            mingw-w64-x86_64-toolchain
            mingw-w64-x86_64-glib2
            mingw-w64-x86_64-pixman
            mingw-w64-x86_64-SDL2
            mingw-w64-x86_64-openssl
            mingw-w64-x86_64-ninja
      - name: Build
        shell: msys2 {0}
        run: |
          git submodule update --init --recursive || true
          mkdir build
          cd build
          ../configure --enable-sdl --disable-cocoa --target-list=arm-softmmu --disable-capstone --disable-slirp --disable-pie --extra-cflags=-I/mingw64/include/openssl --extra-ldflags='-L/mingw64/lib -lcrypto' --disable-stack-protector --disable-werror
          make
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: qemu-windows-x86_64
          path: build/qemu-system-arm.exe

  linux-arm64:
    runs-on: ubuntu-22.04-arm
    needs: release
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          pacman -Syu --noconfirm
          sudo pacman -S --noconfirm  --needed make ninja pkgconf openssl sdl2 pixman glib2 python-pip
          python3 -m pip install --break-system-packages distlib setuptools wheel
      - name: Configure & build
        run: |
          mkdir build
          cd build
          ../configure --enable-sdl --disable-cocoa --target-list=arm-softmmu --disable-capstone --disable-slirp --extra-cflags=-I/usr/include/openssl --extra-ldflags='-lcrypto' --disable-werror --enable-pie
          make
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: qemu-linux-arm64
          path: build/arm-softmmu/qemu-system-arm
    
